"""
Weekly statistics service.

Computes weekly nutrition summary for a user (Mon–Sun of the preceding week).
Used by:
  - Morning scheduler on Mondays (replaces daily summary)
  - /export command (generates .txt file)

All calculations are rule-based — no LLM calls.
The weekly tip (advice based on weekly data) is generated by build_weekly_tip(),
which returns a rule-based recommendation like the morning summary service.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Sequence


@dataclass
class WeeklyData:
    """Aggregated stats for a single day within the week."""
    day: date
    calories: float
    protein_g: float
    fat_g: float
    carbs_g: float
    meals_count: int


@dataclass
class WeekSummary:
    start_date: date
    end_date: date
    days_logged: int            # days with at least 1 meal
    avg_calories: float
    avg_protein_g: float
    avg_fat_g: float
    avg_carbs_g: float
    daily: list[WeeklyData]     # 7 entries, in order Mon→Sun
    best_day: date | None       # closest to targets, or None


_RU_WEEKDAYS = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]
_RU_MONTHS = {
    1: "янв", 2: "фев", 3: "мар", 4: "апр",
    5: "май", 6: "июн", 7: "июл", 8: "авг",
    9: "сен", 10: "окт", 11: "ноя", 12: "дек",
}


def _fmt_date(d: date) -> str:
    return f"{d.day} {_RU_MONTHS[d.month]}"


def compute_week_summary(
    week_data: list[WeeklyData],
    target_calories: float,
    target_protein_g: float,
    target_fat_g: float,
    target_carbs_g: float,
) -> WeekSummary:
    """
    Compute weekly aggregate from a list of 7 WeeklyData entries (Mon–Sun).
    """
    logged = [d for d in week_data if d.meals_count > 0]
    days_logged = len(logged)

    if days_logged == 0:
        start = week_data[0].day
        end = week_data[-1].day
        return WeekSummary(
            start_date=start, end_date=end, days_logged=0,
            avg_calories=0, avg_protein_g=0, avg_fat_g=0, avg_carbs_g=0,
            daily=week_data, best_day=None,
        )

    avg_cal = sum(d.calories for d in logged) / days_logged
    avg_prot = sum(d.protein_g for d in logged) / days_logged
    avg_fat = sum(d.fat_g for d in logged) / days_logged
    avg_carbs = sum(d.carbs_g for d in logged) / days_logged

    # Best day: closest to targets using composite distance
    best_day: date | None = None
    if target_calories > 0:
        def _score(d: WeeklyData) -> float:
            cal_dist = abs(d.calories - target_calories) / target_calories
            prot_dist = abs(d.protein_g - target_protein_g) / target_protein_g if target_protein_g > 0 else 0
            fat_dist = abs(d.fat_g - target_fat_g) / target_fat_g if target_fat_g > 0 else 0
            carbs_dist = abs(d.carbs_g - target_carbs_g) / target_carbs_g if target_carbs_g > 0 else 0
            return cal_dist * 0.5 + prot_dist * 0.3 + fat_dist * 0.1 + carbs_dist * 0.1

        best_day = min(logged, key=_score).day

    return WeekSummary(
        start_date=week_data[0].day,
        end_date=week_data[-1].day,
        days_logged=days_logged,
        avg_calories=avg_cal,
        avg_protein_g=avg_prot,
        avg_fat_g=avg_fat,
        avg_carbs_g=avg_carbs,
        daily=week_data,
        best_day=best_day,
    )


def build_weekly_tip(
    summary: WeekSummary,
    target_calories: float,
    target_protein_g: float,
    target_fat_g: float,
    target_carbs_g: float,
) -> str:
    """Rule-based weekly recommendation based on week averages."""
    if summary.days_logged == 0 or target_calories <= 0:
        return "Записывай питание регулярно — и я смогу дать конкретный совет на следующую неделю."

    cal_ratio = summary.avg_calories / target_calories
    prot_ratio = summary.avg_protein_g / target_protein_g if target_protein_g > 0 else 1.0
    fat_ratio = summary.avg_fat_g / target_fat_g if target_fat_g > 0 else 1.0

    if prot_ratio < 0.75:
        deficit_g = int(target_protein_g - summary.avg_protein_g)
        return (
            f"В среднем не хватало ~{deficit_g}г белка в день — "
            "попробуй добавить по 1 яйцу к завтраку и 100г курицы к обеду, "
            "это закроет разрыв почти полностью."
        )
    if fat_ratio > 1.25:
        return (
            "Жиров было многовато всю неделю — "
            "замени жареное на запечённое 2–3 раза в неделю, "
            "это снизит потребление жиров на 15–20% без потери вкуса."
        )
    if cal_ratio < 0.8:
        return (
            "Калорий было маловато — старайся не пропускать приёмы. "
            "Добавь питательный перекус: горсть орехов или стакан кефира с хлебцем."
        )
    if cal_ratio > 1.2:
        return (
            "Немного выходил(а) за норму по калориям — "
            "попробуй добавить больше овощей в каждый приём: "
            "они дают объём и сытость при минимуме калорий."
        )
    if summary.days_logged < 5:
        return (
            f"Записано только {summary.days_logged} из 7 дней — "
            "чем больше дней ведёшь дневник, тем точнее можно настроить питание."
        )
    return (
        "Хорошая неделя! Постарайся сохранить этот ритм — "
        "регулярность в питании важнее идеальных цифр."
    )


def build_weekly_message(
    name: str,
    summary: WeekSummary,
    target_calories: float,
    target_protein_g: float,
    target_fat_g: float,
    target_carbs_g: float,
    tip: str | None = None,
) -> str:
    """
    Build the Monday morning weekly summary as HTML string.

    Returns a short "not enough data" message if days_logged < 2.
    """
    if summary.days_logged < 2:
        week_str = f"{_fmt_date(summary.start_date)}–{_fmt_date(summary.end_date)}"
        return (
            f"📊 Твоя неделя: {week_str}\n\n"
            f"Записано: {summary.days_logged} из 7 дней — маловато для аналитики.\n\n"
            f"Попробуй на этой неделе записывать хотя бы 3 дня, "
            f"и я покажу полную динамику 📊"
        )

    week_str = f"{_fmt_date(summary.start_date)}–{_fmt_date(summary.end_date)}"
    greeting = f"☀️ Доброе утро, {name}!\n\n" if name else "☀️ Доброе утро!\n\n"

    # Header
    header = f"📊 Твоя неделя: {week_str}"

    # Key stats
    def _status(avg: float, target: float) -> str:
        if target <= 0:
            return ""
        ratio = avg / target
        if ratio < 0.85:
            return " — чуть не хватает"
        if ratio > 1.15:
            return " — немного много"
        return " — ✅ в норме"

    prot_status = _status(summary.avg_protein_g, target_protein_g)
    fat_status = _status(summary.avg_fat_g, target_fat_g)
    carbs_status = _status(summary.avg_carbs_g, target_carbs_g)

    cal_target_str = f" (цель: {int(target_calories)})" if target_calories > 0 else ""
    stats = (
        f"Записано дней: {summary.days_logged} из 7\n"
        f"Среднее за день: {int(summary.avg_calories)} ккал{cal_target_str}\n"
        f"Белки: в среднем {int(summary.avg_protein_g)}г/день{prot_status}\n"
        f"Жиры: в среднем {int(summary.avg_fat_g)}г/день{fat_status}\n"
        f"Углеводы: в среднем {int(summary.avg_carbs_g)}г/день{carbs_status}"
    )

    # Day-by-day dynamics (compact one-liner)
    dynamics_parts: list[str] = []
    for d in summary.daily:
        wd_label = _RU_WEEKDAYS[d.day.weekday()]
        if d.meals_count > 0:
            dynamics_parts.append(f"{wd_label} — {int(d.calories)}")
        else:
            dynamics_parts.append(f"{wd_label} — ✖️")
    dynamics = "📈 Динамика:\n" + " · ".join(dynamics_parts)

    sections = [greeting + header, stats, dynamics]

    # Best day
    if summary.best_day:
        best_wd = _RU_WEEKDAYS[summary.best_day.weekday()]
        sections.append(f"🏆 Лучший день: {best_wd}, {_fmt_date(summary.best_day)}")

    # Weekly tip
    week_tip = tip or build_weekly_tip(
        summary, target_calories, target_protein_g, target_fat_g, target_carbs_g
    )
    sections.append(f"💡 Совет на неделю: {week_tip}")

    return "\n\n".join(sections)


def build_txt_export(
    name: str,
    week_meals: dict[date, list[dict]],
    week_data: list[WeeklyData],
    start_date: date,
    end_date: date,
    target_calories: float,
    target_protein_g: float,
    target_fat_g: float,
    target_carbs_g: float,
) -> str:
    """
    Build a plain-text export for the week.

    week_meals: {date: list of meal dicts with keys
                 logged_at, calories, protein_g, fat_g, carbs_g, meal_items}
    week_data: daily aggregates (WeeklyData list)
    """
    _FULL_MONTHS = {
        1: "января", 2: "февраля", 3: "марта", 4: "апреля",
        5: "мая", 6: "июня", 7: "июля", 8: "августа",
        9: "сентября", 10: "октября", 11: "ноября", 12: "декабря",
    }
    _FULL_WEEKDAYS = ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"]

    lines: list[str] = []
    title = f"Дневник питания: {start_date.day} {_FULL_MONTHS[start_date.month]}–{end_date.day} {_FULL_MONTHS[end_date.month]} {end_date.year}"
    if name:
        title += f"\nПользователь: {name}"
    lines.append(title)
    lines.append("")

    # Daily detail
    current = start_date
    agg_by_date = {d.day: d for d in week_data}
    while current <= end_date:
        wd = _FULL_WEEKDAYS[current.weekday()]
        day_str = f"{current.day} {_FULL_MONTHS[current.month]}"
        lines.append(f"{wd}, {day_str}")
        lines.append("─" * 40)

        meals_today = week_meals.get(current, [])
        if not meals_today:
            lines.append("(нет записей)")
        else:
            for m in sorted(meals_today, key=lambda x: x.get("logged_at") or ""):
                logged_at = m.get("logged_at")
                time_str = logged_at.strftime("%H:%M") if hasattr(logged_at, "strftime") else ""
                cal = int(m.get("calories", 0))
                prot = m.get("protein_g", 0)
                fat = m.get("fat_g", 0)
                carbs = m.get("carbs_g", 0)

                items = m.get("meal_items") or []
                if items:
                    item_names = ", ".join(
                        it.get("name", "") for it in items if it.get("name")
                    )
                    prefix = f"{time_str}: {item_names}" if time_str else item_names
                else:
                    prefix = time_str or "Приём"

                lines.append(
                    f"{prefix} — {cal} ккал · Б {prot:.0f}г · Ж {fat:.0f}г · У {carbs:.0f}г"
                )

        daily = agg_by_date.get(current)
        if daily and daily.meals_count > 0:
            lines.append(
                f"Итого: {int(daily.calories)} ккал · Б {daily.protein_g:.0f}г · "
                f"Ж {daily.fat_g:.0f}г · У {daily.carbs_g:.0f}г"
            )

        lines.append("")
        current += timedelta(days=1)

    # Weekly totals
    lines.append("ИТОГИ НЕДЕЛИ")
    lines.append("─" * 40)
    logged_days = [d for d in week_data if d.meals_count > 0]
    days_logged = len(logged_days)
    if days_logged > 0:
        avg_cal = sum(d.calories for d in logged_days) / days_logged
        avg_prot = sum(d.protein_g for d in logged_days) / days_logged
        avg_fat = sum(d.fat_g for d in logged_days) / days_logged
        avg_carbs = sum(d.carbs_g for d in logged_days) / days_logged
        lines.append(f"Записано дней: {days_logged} из 7")
        lines.append(f"Средняя калорийность: {int(avg_cal)} ккал/день")
        if target_calories > 0:
            lines.append(f"Цель: {int(target_calories)} ккал/день")
        lines.append(f"Средние белки: {avg_prot:.0f}г/день")
        lines.append(f"Средние жиры: {avg_fat:.0f}г/день")
        lines.append(f"Средние углеводы: {avg_carbs:.0f}г/день")
    else:
        lines.append("Записей за неделю нет.")

    return "\n".join(lines)
